### ISSUE TITLE
ES Modules imported

### ISSUE THREAD

**Issue by Blindmikey** [blaise-io/live-reload#12]
/src/components/*.js
/src/app.js

app.js imports ES modules exported by js files under /src/components
However with the rules above, only app.js is being detected. 
/src/components js files are being loaded as per network inspector

If I add script tags for those component js files, live-reload does pick up on them and detect changes. So changes are only detected if the script is referenced in the html markup. Not sure if this limitation is inherent to this implementation.

**Comment by blaise-io** [comment]
At the moment the JavaScript files have to be included by the HTML file in order to be detected for monitoring. This may be too limited, as demonstrated by your issue. 

I should be able to fix that by implementing [WebRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest) in [https://github.com/blaise-io/live-reload/blob/7e435ce084f0a83f5778d10a164104797c68cd59/app/background.ts#L115](monitorTabIfRuleMatch).

**Comment by blaise-io** [comment]
This should now work in 1.8.0 if you're on Firefox.
1.8.0 for Chrome is pending review in the Chrome app store.
