### ISSUE TITLE
link[rel=stylesheet] in inject.ts doesn't pick up preloaded stylesheets

### ISSUE THREAD

**Issue by rotkohlsuppe** [blaise-io/live-reload#28]
`const selector = document.querySelectorAll("link[rel=stylesheet]");`

I'd suggest to use a broader selector like: 
`document.querySelectorAll("link[rel*=stylesheet], link[rel=preload][as=style]")`
for all possiblities, like 
`<link rel="preload stylesheet" href="...css">` and 
`<link rel="preload" as="style" href="...css">`.

[Preload @MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload)

**Comment by blaise-io** [comment]
Thanks, good suggestion, I will fix this soon.

**Comment by blaise-io** [comment]
@rotkohlsuppe I'm now supporting `<link rel="preload stylesheet" href="...css">` when inline reloading css resources. However, it doesn't make sense to support  `<link rel="preload" as="style" href="...css">` because the document is already past the preloading phase when reloading inline resources. Note that the selector is not used to *detect* which resources are monitored, for this I intercept http requests.

**Comment by blaise-io** [comment]
This will be in 1.8.4
