### ISSUE TITLE
Not working for me with file:// URLs

### ISSUE THREAD

**Issue by Yolo-Jerome** [blaise-io/live-reload#3]
(sorry I also was #2 but I used the wrong account)

It is not working for me unfortunately.

I'm using Doxygen 1.8.13 to generate .html, .css, .js and .png files to a folder lets say
`file:///C:/html/`

So in the PlugIn I configured the following Paths:
Host URL:
`file:///C:/html/*.html`

Source file URLs
`file:///C:/html*`

Monitor source URLs every [` 2 `] seconds

But after a new build from Doxgen the page gets never reloaded.

**Comment by blaise-io** [comment]
Due to security restrictions in Firefox extensions, I cannot access the local filesystem to monitor for file changes. I will clarify this in the documentation and within the extension.

A workaround is to serve files using http using [url=https://stackoverflow.com/a/15328771/451480]Python[/url] or [url=https://stackoverflow.com/a/16350826/451480]NodeJs[/url].

**Comment by blaise-io** [comment]
Oops, still have to add some detection in the form.

**Comment by blaise-io** [comment]
Implemented in 1.4.2.

**Comment by sdudnic** [comment]
so where is the clarification in the documentation? why this is not mentionned when we install this plugin?

**Comment by blaise-io** [comment]
It was a convenient side effect of an approach used in an earlier version.

**Comment by sdudnic** [comment]
i installed this to monitor my file changes, it name is live-reload... this does not monitor the file changes, I am dissapointed, I uninstalled this, what a deception...

**Comment by blaise-io** [comment]
I hope you didn’t pay for it!

**Comment by sdudnic** [comment]
I paid my time.
